<?php

/**
 * These wrapper functions are needed because ctools_wizard_multistep_form
 * can only handle function callbacks.
 */

/**
 * Form callback
 */
function oowizard_form($form, &$form_state) {
  return $form_state['oowizard']->form($form, $form_state);
}

/**
 * Validate callback
 */
function oowizard_form_validate($form, &$form_state) {
  return $form_state['oowizard']->validate($form, $form_state);
}

/**
 * Submit callback.
 */
function oowizard_form_submit($form, &$form_state) {
  $form_state['oowizard']->submit($form, $form_state);
}

/**
 * Implements hook_theme()
 */
function oowizard_theme() {
  $theme['oowizard_trail'] = array(
    'variables' => array('trail' => array()),
  );
  return $theme;
}

/**
 * HTML-Output for the wizard trail.
 * @TODO: put this in a separate file.
 */
function theme_oowizard_trail(&$vars) {
  $trail = $vars['trail'];

  $position = 'previous';
  $html = array();

  foreach ($trail as &$t) {
    if ($position = 'current' && !$t['current'])
      $class = 'next';
    if ($t['current'] && $t['current'])
      $class = 'current';

    if ($t['accessible']) {
      $options['attributes']['class'] = array('inner');
      $link = l($t['title'], $t['url'], $options);
    } else {
      $link = "<span class=\"inner\">{$t['title']}</span>";
    }
    $html[] = "<span class=\"wizard-trail-$class\">$link</span>";
  }
  if (!empty($html)) {
    return '<div class="wizard-trail-wrapper"><div class="wizard-trail">' . implode('', $html) . '</div></div>';
  }
}
